### ISSUE TITLE
Unable to locate the extension.

### ISSUE THREAD

**Issue by aethatsme** [georgebabarus/magento-filesystem-extension#19]
I'm unable to locate the filesystem extension in the marketplace. Is it labeled under a different name by any chance?

**Comment by georgebabarus** [comment]
Hi @aethatsme 

Unfortunately, the publishing process is not finished.

There are 2 extensions in the Marketing Review step in Magento Marketplace with the following names:

- "Remote Filesystem Integration" - the main extension providing extended API for remote filesystem integration and configuration provider 
- "Amazon S3 Integration Filesystem Driver" - implementation of Amazon S3 API (also compatible with Digital Ocean SPACES OBJECT STORAGE)

The others extensions/features described in the documentation/roadmap are not yet ready to publish: https://docs.magento.asset42.com/en/latest/roadmap.html

**Comment by georgebabarus** [comment]
Hi @aethatsme, 

The first two extensions have been published in Magento Marketplace:

* https://marketplace.magento.com/bb-filesystem.html
* https://marketplace.magento.com/bb-filesystem-s3.html

And could be used for custom development.
